/*============================================================
        Headfile about Habit of Frank   V1.00
==============================================================
Function:				Define some Habit of Frank
Writer:					Frank
Data:						2009.3.31
=============================================================*/

#ifndef _Habit_Frank_H_
#define _Habit_Frank_H_

//********************* 
//* 用户类型定义区    * 
//*********************
typedef unsigned char  u08;
typedef unsigned int 	u16;
typedef unsigned long int 	u32;

#endif